## LoRA (Low-Rank Adaptation)

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 14.9 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.6 MB 17.6 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.6 MB 12.8 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 12.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 11.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [13]:
# Original weight matrix
W0 = np.array([[1, 2, 3],
                [4, 5, 6]])

# Low-rank matrices
A = np.array([[0.1, 0.2]])  # Shape: (1, 2)
B = np.array([[0.3],
              [0.4],
              [0.5]])  # Shape: (3, 1)

# LoRA update
delta_W = np.dot(A.T, B.T)

# Final adapted weight
W = W0 + delta_W

print("Original W0:")
print(W0)
print("\nLoRA update (ΔW):")
print(delta_W)
print("\nFinal adapted W:")
print(W)

Original W0:
[[1 2 3]
 [4 5 6]]

LoRA update (ΔW):
[[0.03 0.04 0.05]
 [0.06 0.08 0.1 ]]

Final adapted W:
[[1.03 2.04 3.05]
 [4.06 5.08 6.1 ]]


## AdaLoRA (Adaptive LoRA)

In [5]:
# Original weight matrix
W0 = np.array([[1, 2, 3],
                [4, 5, 6]])

# Simulated SVD components
P = np.array([[0.1, 0.2],
              [0.3, 0.4]])  # Left singular vectors
Lambda = np.array([0.5, 0.3])  # Singular values
Q = np.array([[0.6, 0.7, 0.8],
              [0.9, 1.0, 1.1]])  # Right singular vectors

# AdaLoRA update
delta_W = np.dot(P * Lambda, Q)

# Final adapted weight
W = W0 + delta_W

print("Original W0:")
print(W0)
print("\nAdaLoRA update (ΔW):")
print(delta_W)
print("\nFinal adapted W:")
print(W)

# Simulating importance-based pruning
Lambda_pruned = np.array([0.5, 0])  # Prune the less important singular value
delta_W_pruned = np.dot(P * Lambda_pruned, Q)

print("\nPruned AdaLoRA update (ΔW):")
print(delta_W_pruned)

Original W0:
[[1 2 3]
 [4 5 6]]

AdaLoRA update (ΔW):
[[0.084 0.095 0.106]
 [0.198 0.225 0.252]]

Final adapted W:
[[1.084 2.095 3.106]
 [4.198 5.225 6.252]]

Pruned AdaLoRA update (ΔW):
[[0.03  0.035 0.04 ]
 [0.09  0.105 0.12 ]]


 ## IA³ (Infused Adapter by Inhibiting and Amplifying Inner Activations)

In [6]:
# Original activations
x = np.array([[1, 2, 3],
              [4, 5, 6]])

# Learned rescaling vector
l = np.array([0.5, 1.5, 1.0])

# IA³ rescaling
y = x * l  # Element-wise multiplication

print("Original activations:")
print(x)
print("\nRescaling vector:")
print(l)
print("\nRescaled activations:")
print(y)

Original activations:
[[1 2 3]
 [4 5 6]]

Rescaling vector:
[0.5 1.5 1. ]

Rescaled activations:
[[0.5 3.  3. ]
 [2.  7.5 6. ]]


## LoHa (Low-Rank Hadamard Product)

In [7]:
# Original weight matrix
W0 = np.array([[1, 2, 3],
                [4, 5, 6]])

# Low-rank matrices
A1 = np.array([[0.1, 0.2]])
B1 = np.array([[1.0],
               [1.1],
               [1.2]])

A2 = np.array([[0.3, 0.4]])
B2 = np.array([[1.3],
               [1.4],
               [1.5]])

# LoHa update
delta_W1 = np.dot(A1.T, B1.T)
delta_W2 = np.dot(A2.T, B2.T)
delta_W = delta_W1 * delta_W2  # Hadamard product

# Final adapted weight
W = W0 + delta_W

print("Original W0:")
print(W0)
print("\nLoHa update (ΔW):")
print(delta_W)
print("\nFinal adapted W:")
print(W)

Original W0:
[[1 2 3]
 [4 5 6]]

LoHa update (ΔW):
[[0.039  0.0462 0.054 ]
 [0.104  0.1232 0.144 ]]

Final adapted W:
[[1.039  2.0462 3.054 ]
 [4.104  5.1232 6.144 ]]


## LoKr (Low-Rank Kronecker Product)

In [12]:
# Original weight matrix
W0 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])  # Shape: (2, 4)

# Low-rank matrices
A = np.array([[0.1], [0.2]])  # Shape: (2, 1)
B = np.array([[1.0, 1.1, 1.2, 1.3]])  # Shape: (1, 4)

# LoKr update
delta_W = np.kron(A, B)  # Kronecker product, shape will be (2, 4)

# Optional third matrix (must match the shape of delta_W)
C = np.array([[0.9, 1.1, 0.8, 1.2],
              [1.0, 0.9, 1.1, 0.7]])  # Shape: (2, 4)

# Element-wise multiplication with optional matrix
delta_W = delta_W * C

# Final adapted weight
W = W0 + delta_W

print("Original W0:")
print(W0)
print("\nKronecker product result (A ⊗ B):")
print(delta_W)
print("\nAfter element-wise multiplication with C:")
print(delta_W)
print("\nFinal adapted W:")
print(W)

Original W0:
[[1 2 3 4]
 [5 6 7 8]]

Kronecker product result (A ⊗ B):
[[0.09  0.121 0.096 0.156]
 [0.2   0.198 0.264 0.182]]

After element-wise multiplication with C:
[[0.09  0.121 0.096 0.156]
 [0.2   0.198 0.264 0.182]]

Final adapted W:
[[1.09  2.121 3.096 4.156]
 [5.2   6.198 7.264 8.182]]
